name: Deploy to Development

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to Development Server
        run: |
          cd ~/workspace/env
          git pull
          ./gt-main/update.sh dev
